hit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^fixHIT$', views.fixHIT, name='fixHIT'),
    url(r'^checkHIT$', views.checkHIT, name='checkHIT'),
]

hitrequest/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index.html$', views.index, name='index'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^deleteAll/$', views.deleteAll, name='deleteAll'),
    url(r'^deleteAllHits/$', views.deleteAllHits, name='deleteAllHits'),
    url(r'^approveAllHits/$', views.approveAllHits, name='approveAllHits'),
]

transcroobie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^hit/', include('hit.urls')),
    url(r'^hitrequest/', include('hitrequest.urls', namespace='hitrequest')),
    url(r'^$', RedirectView.as_view(pattern_name='hitrequest:index', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.login, name='logout'), # logout redirects to in
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hitrequest/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.fields import JSONField

class AudioSnippet(models.Model):
    audio = models.FileField(upload_to='audioparts/%Y-%m-%d')

    # Predictions: each item in the list is a transcription (automatic or AMT)
    predictions = ArrayField(
        models.TextField(blank=True),
        default = []
    )

    # List of incorrectly transcribed words (as determined by AMT)
    # Can't be a multi-d array because it would not be rectangular
    incorrectWords = JSONField( default = {'bools': [] })

    # Has the last prediction been validated?
    activeHITId = models.CharField(max_length=30)

    # Has the last prediction been validated?
    hasBeenValidated = models.BooleanField(default=False)

    # Are we done looking at this HIT? (Potentially given up without validation?)
    isComplete = models.BooleanField(default=False)

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

    # list of audio snippets
    audioSnippets = ArrayField(
        models.ForeignKey(AudioSnippet)
    )
    audioSnippets = models.ManyToManyField('hitrequest.AudioSnippet',
                                           related_name='docForSnippet')

    completeTranscript = models.TextField(blank=True)

hitrequest/forms.py
from django import forms

class DocumentForm(forms.Form):
    uploadedFile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

hitrequest/views.py
import os
from urlparse import urlparse
import tempfile

from boto.exception import GSResponseError
from celery.utils.log import get_task_logger
from django.template import loader
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.files.base import File
from django.conf import settings
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required

from hitrequest.models import Document, AudioSnippet
from hitrequest.forms import DocumentForm
from hitrequest.splitAudio import splitAudioIntoParts, validateAudio, AudioError
from hitrequest.createHits import HitCreator
from hitrequest.speechrec import getTranscriptionFromURL
from transcroobie.celery import app

logger = get_task_logger(__name__)

@csrf_exempt
@login_required
def index(request):
    # Handle file upload
    request.upload_handlers.pop(0)
    return _list(request)

@csrf_protect
def _list(request):
    """ This is the trigger to take an uploaded file and create a HIT """
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            uploadedFile = request.FILES['uploadedFile']
            newdoc = Document(docfile = uploadedFile)
            newdoc.save()

            usersFilename = uploadedFile.name
            _, extension = os.path.splitext(usersFilename)

            # Validate the audio immediately
            try:
                _validateUploadedDocument(newdoc.id, extension, usersFilename)
            except AudioError as e:
                return HttpResponse("Invalid Audio: " + str(e))

            # Delay processing so we can return a file soon
            _processUploadedDocument.delay(newdoc.id, extension)

            # Redirect to the document list after POST
            return HttpResponseRedirect('index.html')
    else:
        # Spawn a processHitTask every refresh
        _processHitsTask(doSpawn=False)

        form = DocumentForm() # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.order_by('id').all()

    render_data = {'documents': documents,
                   'form': form}
    template = loader.get_template('hitrequest/list.html')
    response = template.render(render_data, request)

    return HttpResponse(response)

def _getUploadedFile(docId, extension):
    """
        Grabs an uploaded file and returns a tempFile with its contents,
        as well as a pointer to the Model
    """
    newdoc = get_object_or_404(Document, pk = docId)

    tmpFile = tempfile.NamedTemporaryFile(suffix=extension)
    uploadedFile = newdoc.docfile
    with open(tmpFile.name, 'wb+') as dest:
        dest.write(uploadedFile.read())

    return newdoc, tmpFile

def _validateUploadedDocument(docId, extension, usersFilename):
    """
        Verifies that the uploaded document is ready for processing
    """
    newdoc, tmpFile = _getUploadedFile(docId, extension)
    logger.info("Verifying Doc ID %d (%s)" % (docId, usersFilename))

    validateAudio(tmpFile.name, extension)

    logger.info("Doc ID %d (%s) is valid" % (docId, usersFilename))

@app.task(name="_processUploadedDocument")
def _processUploadedDocument(docId, extension):
    # Extension should include leading '.'
    ONLY_USE_GOOGLE = True

    newdoc, tmpFile = _getUploadedFile(docId, extension)
    logger.info("Processing Doc ID %d" % (docId,))

    hitCreator = HitCreator()

    # Get the paths of each of the split fileparts
    i = 0
    for (tmpFileObject, sampleRate) in splitAudioIntoParts(tmpFile.name,
            extension, basedir = settings.MEDIA_ROOT):
        logger.info("   Processing part {}".format(i))
        relPath = os.path.relpath(tmpFileObject, settings.MEDIA_ROOT)

        # Open the file, copy into to the database's storage.
        # TODO - inefficient copying - how can splitAudioIntoParts
        # write directly into the correct location?
        with open(tmpFileObject) as fileObj:
            fileCopy = File(file=fileObj, name=relPath)

            audioModel = AudioSnippet(audio = fileCopy,
                                      hasBeenValidated = False,
                                      predictions = [])

            # Get the transcript
            audioModel.save() # upload fileCopy
            url = "gs://"+settings.GS_BUCKET_NAME+urlparse(audioModel.audio.url).path
            text, confidence = getTranscriptionFromURL(url, sampleRate)
            audioModel.predictions.append(text)

            if float(confidence) > .90:
                audioModel.hasBeenValidated = True

            if ONLY_USE_GOOGLE:
                audioModel.isComplete = True
            else:
                # Create a hit from this document
                hitCreator.createHitFrom(audioModel, 'check')

            newdoc.audioSnippets.add(audioModel) # this sometimes saves audioModel?
            audioModel.save() # but sometimes it doesn't and we need to manually save?

        logger.info("   Completed part  {}".format(i))
        i += 1

    newdoc.save()
    _processHitsTask.apply_async([True, 10],countdown=60) # wait a minute before processing

def _deleteDocument(docToDel):
    hitCreator = None
    for audioSnippet in docToDel.audioSnippets.all():
        audioSnippet.audio.delete()
        if audioSnippet.activeHITId:
            if not hitCreator:
                # delay creation - I think this tries to connect to AMT on init
                hitCreator = HitCreator()
            hitCreator.deleteHit(audioSnippet.activeHITId)
        audioSnippet.delete()
    try:
        # The file may have been deleted remotely or not successfully uploaded
        docToDel.docfile.delete()
    except GSResponseError:
        pass

    docToDel.delete()

@login_required
def delete(request):
    """ Delete one uploaded file """
    if request.method != 'POST':
        raise Http404

    docId = request.POST.get('selectedDoc', None)
    docToDel = get_object_or_404(Document, pk = docId)
    _deleteDocument(docToDel)

    return redirectToIndex()

@login_required
def deleteAll(request):
    """ Delete all uploaded files """
    documents = Document.objects.all()
    for docToDel in documents:
        _deleteDocument(docToDel)

    audioSnippets = AudioSnippet.objects.all()
    for audioSnippet in audioSnippets:
        audioSnippets.delete()

    return redirectToIndex()

@login_required
def deleteAllHits(request):
    hitCreator = HitCreator()
    hitCreator.deleteAllHits()

    return redirectToIndex()

@app.task(name="_processHitsTask")
def _processHitsTask(doSpawn, spawnTimeout=None):
    """ doSpawn: if there are unprocessed HITs, spawn more tasks?
                 be careful not to recursively spawn a zillion jobs. """
    docs = Document.objects.order_by('id')
    hitCreator = HitCreator()
    hasAnyHITCompleted = False
    areAllHITsDone = True
    for doc in docs:
        if doc.completeTranscript:
            continue

        newHITCompleted = hitCreator.processHits(doc)
        hasAnyHITCompleted |= newHITCompleted

        if doc.completeTranscript:
            # Check again after processing
            areAllHITsDone = False

    if doSpawn and not areAllHITsDone:
        assert spawnTimeout
        # If a HIT completes, halve the countdown time.
        # Else, double it.
        nextCountdownMult = 2 if not hasAnyHITCompleted else 0.5
        nextCountdown = spawnTimeout * nextCountdownMult
        if spawnTimeout > 60 * 60 * 24: # one day
            logger.info("Waiting {} seconds before looking for more HITs.".format(
                    nextCountdown))
            _processHitsTask.apply_async([True, nextCountdown], countdown=spawnTimeout)
        else:
            logger.error("Waited a day and still no HITs ready")

@login_required
def approveAllHits(request):
    hitCreator = HitCreator()
    hitCreator.approveAllHits()

    return redirectToIndex()

def redirectToIndex():
    return HttpResponseRedirect('../index.html')

templates/hitrequest/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Upload files to transcribe</title>
    </head>
{% load static %}
<link rel="stylesheet" href="{% static "style.css" %}"/>

<!-- Upload button, from http://maffrigby.com/nice-file-upload-button-dude/ -->
<style>
.fileUpload {
	position: relative;
	overflow: hidden;
	margin: 10px;
}
.fileUpload input.upload {
	position: absolute;
	top: 0;
	right: 0;
	margin: 0;
	padding: 0;
	font-size: 20px;
	cursor: pointer;
	opacity: 0;
	filter: alpha(opacity=0);
}
</style>
    <body>
    <h1>Transcroobie</h1>
    <h4>¡{{ user.username }}! <a href="../../logout" name="white">(logout?)</a></h4>

    <!-- List of uploaded documents -->
    {% if documents %}
        <ul>
        {% for document in documents %}
<table>
    <thead>
        <tr>
            <th>
            <form action="{% url 'hitrequest:delete' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="selectedDoc" value="{{ document.pk }}" />
                <input type="submit" value="[x]" />
            </form>
            </th>
            <th>
                <a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a>
            </th>
            <th>
                {% if document.completeTranscript %}
                {{ document.completeTranscript }}
                {% else %}
                Pending Prediction
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
            {% for audiosnippet in document.audioSnippets.all %}
        <tr>
            <td style="text-align:center">
                {% if audiosnippet.hasBeenValidated %}
                    ✔️
                {% elif audiosnippet.isComplete %}
                    ❌
                {% elif audiosnippet.predictions|length == audiosnippet.incorrectWords.bools|length%}
                    <a href='../../hit/fixHIT?docId={{audiosnippet.pk}}&assignmentId=ASSIGNMENT_ID_NOT_AVAILABLE&hitId={{audiosnippet.activeHITId}}'>🔨</a>
                {% else %}
                    <a href='../../hit/checkHIT?docId={{audiosnippet.pk}}&assignmentId=ASSIGNMENT_ID_NOT_AVAILABLE&hitId={{audiosnippet.activeHITId}}'>🏷</a>
                {% endif %}
            </td>
            <td>
                <a href="{{ audiosnippet.audio.url }}">{{ audiosnippet.audio.name }}</a>
            </td>
            <td>
                {% for prediction in audiosnippet.predictions %}
                    <br/><strong>Prediction #{{ forloop.counter }}</strong>:
                    {{prediction}}
                    <br/>
                {% endfor %}
                <p />
                {% if audiosnippet.activeHITId %}
                <strong>Active HIT ID:</strong> {{ audiosnippet.activeHITId }}
                {% endif %}
            </td>
        </tr>
            {% endfor %}
    </tbody>
</table>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <table width=400><thead><tr><th>
        <h2> Upload a new audio file </h2>
        <form action="{% url 'hitrequest:index' %}" method="post" enctype="multipart/form-data" class="fileUpload">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.uploadedFile.label_tag }} {{ form.uploadedFile.help_text }}</p>
            <p>
                {{ form.uploadedFile.errors }}
                {{ form.uploadedFile }}
            </p>
            <center><input type="submit" value="Upload" /></center>
        </form>
        </th></tr></thead></table>


        <table width=400><thead><tr><th style="text-align:center">
        <h2> Extra controls </h2>
        <form action="{% url 'hitrequest:approveAllHits' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Approve completed AMT HITs" />
        </form>
        <form action="{% url 'hitrequest:deleteAllHits' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Delete all AMT HITs" />
        </form>
        <form action="{% url 'hitrequest:deleteAll' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="submit" value="Delete all files" />
        </form>
        </th></tr></thead></table>
    </body>
</html> 

templates/hitrequest/text.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Generic text</title>
    </head>
    <body>
        <div>
            {{ processedHitText|linebreaks }}
        </div>

        <a href="{% url 'list' %}">Back to list</a>
    </body>
</html> 